apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
    field.cattle.io/creatorId: user-mzmqd
  creationTimestamp: 2019-04-04T23:22:38Z
  generation: 20
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-splitter-splitter
  name: splitter
  namespace: splitter
  resourceVersion: "176705"
  selfLink: /apis/apps/v1beta2/namespaces/splitter/deployments/splitter
  uid: 894a1d71-5730-11e9-b073-025000000001
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-splitter-splitter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2019-04-09T03:23:36Z
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-splitter-splitter
    spec:
      containers:
      - env:
        - name: HOSTNAME
          value: 172.20.10.5
        - name: POOL
          value: "5"
        - name: SPLIT
          value: "50000"
        image: localhost:5000/splitter:v2.3.4
        imagePullPolicy: Always
        name: splitter
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /Users/interware/Documents/IW/PROSA/Match-Interredes/Lab
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /Users/interware/Documents/IW/PROSA/Match-Interredes/Lab
          type: DirectoryOrCreate
        name: vol1
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-04-08T14:34:38Z
    lastUpdateTime: 2019-04-08T14:34:38Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-04-04T23:22:38Z
    lastUpdateTime: 2019-04-09T03:26:16Z
    message: ReplicaSet "splitter-74d5b6dc44" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 20
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

